{
    "type":"Feature",
    "properties":{
        "NAME":"CCSS Buildin",
        "NAMEASCII":"CCSS Buildin",
        "ELEVATION": 0.00000
    },
    "geometry": {
        "type":"Polygon",
        "coordinates": [[
            [ 120.98999216, 14.60203212 ],
            [ 120.98982709, 14.60196665 ],
            [ 120.98995851, 14.60162114 ],
            [ 120.99012629, 14.60167045 ],
            [ 120.98999216, 14.60203212 ]
        ]]
    }
}
